[package]
name = "palette-rs"
description = "A little utility to display your ansi colour palette"
version = "0.1.0"
authors = ["Pierre Chevalier <pierrechevalier83@gmail.com>"]
license = "MIT"

[dependencies]
matrix_display = "0.4"
